### PR TITLE
More stuff

### PR DESCRIPTION
**Pull request by crishaddad**
Fixed a few small things; Improved 2 icons from my previous PR; Added a few new icons (including some low-hanging fruit from #117 #119)

### CODE REVIEW

**Comment by crishaddad** [comment]
I'm starting to get a bit better at using Inkscape :)

**Comment by dkanada** [comment]
Yeah the icons are looking really good! A lot of these icons were very sorely needed here so thanks for taking the time to add them :)

**Comment by dkanada** [comment]
By the way, I have a few tricks to make the additions go a lot faster. A lot of the time Ameixa will have perfectly good icons [here](https://gitlab.com/xphnx/ameixa/tree/master/icons) that just need the square removed and color changed to white to work perfectly in Frost. @suffixdesign if you want to work on the todo list or any other icons it is super easy to check Ameixa and see if they have a decent icon. I also often try to simplify the designs when I am adding icons, such as in c:geo, Slide, and Nova Launcher. The other main thing I sometimes like to do is remove icons with unnecessary outer shapes, like Threema and Blogger. @crishaddad you could probably do this with Periodical if you like that look better.

**Comment by crishaddad** [comment]
> @crishaddad you could probably do this with Periodical if you like that look better.

I will see how it looks once it comes through to my phone, and maybe update it. I used the rectangle-outline-with-cutout in order to try and force some consistency with the rest of the pack. I noticed after my first lot of icons came through to me, some were noticeably different in style (especially size) from the ones that were already there. This is represented e.g. in the way that I have resized the "share to clipboard" to fit into the space given by the rectangle template, rather than to fill 48x48 as it originally did.

**Comment by dkanada** [comment]
This looks great, thanks. You seem pretty familiar with the workflow now so you can just add any additions to the `icons` folder. One thing to note, the `xml.sh` script automatically generates `drawable.xml` and `iconpack.xml` from the icons folder, so if you have been doing that manually there's no need :)

**Comment by suffixdesign** [comment]
i have trouble after the first merge. i created new icons, but i don't know what to do. should i merge, create a new pull, or something else? i'm not familiar with github.

so, i'm not pretty familiar with the workflow. ;)
also i'd like to revise my additions as you've done it previously, as they're not to expectations.

b.

-------------------------------------
-- Eredeti üzenet --
Feladó: dkanada&lt;notifications@github.com&gt;Címzett: dkanada/frost&lt;frost@noreply.github.com&gt;Elküldve: 2018. november 8. 11:11Tárgy : Re: [dkanada/frost] More stuff (#125)


This looks great, thanks. You seem pretty familiar with the workflow now so you can just add any additions to the icons folder. One thing to note, the xml.sh script automatically generates drawable.xml and iconpack.xml from the icons folder, so if you have been doing that manually there's no need :)

**Pull request merged**
