### PR TITLE
New Icons

### PR DESCRIPTION
**Pull request by MicrosoftTakeover**
I've never used Inkscape before now, hope these icons are done properly!

ADB Manager
f.lux
Markor
OS Monitor
SkyTube
Twire
wX

### CODE REVIEW

**Comment by MicrosoftTakeover** [comment]
Update appfilter to use the default "files" icon for the Ghost Commander app.

**Comment by MicrosoftTakeover** [comment]
Whoops, forgot to remove the reference raster image layer from a couple of the icons, fixed that.

Also created a new icon for Scarlet Notes FD by utilizing an image to SVG converter instead of creating it completely from scratch like the others. I'm pleased with the result.

**Comment by MicrosoftTakeover** [comment]
Added icon for Ghost Commander

**Comment by dkanada** [comment]
These look great, merging now. Sorry it took so long to get to this PR, I've been busy this month :)

**Pull request merged**
