### PR TITLE
Some new & updated icons!

### PR DESCRIPTION
**Pull request by Donnnno**
**Updated:** signal & Instagram icons
**Added:**
Teams, 
Audio technica connect
Surfshark
EDS-Lite
GeekRSS
Librera Reader
ScanBot
Tiny Tiny RSS
Simple Voice Recorder

**Updated appfilter:** Bundled the Microsoft apps together

afbeelding

### CODE REVIEW

**Comment by nonnominandus** [comment]
I seem to also have created a Teams icon (#297). I gave it a T which is very similar to the other office icons (I used roboto medium in them), added a gap between the two persons, and used the exact same cutout that is also used in the other office apps.
rect1976

I guess we have to debate which icon to take.

**Comment by Donnnno** [comment]
> 
> 
> I seem to also have created a Teams icon (#297) because I did not see you already created one. I gave it a T which is very similar to the other office icons (I used roboto medium in them), added a gap between the two persons, and used the exact same cutout that is also used in the other office apps.
> rect1976
> 
> I guess we have to debate which icon to take.

Hey nice! The first thing I noticed is this: 
are the uneven spaces in your take, also the rounded corners have the same values now, that makes it out of balance.
(I used Segoe UI, the font that microsoft uses for the icon)
My suggestion would be to use mine but with roboto and the gap between the persons. Let me know what you think.
I've fixed those things in the past for other office icons btw.
afbeelding

**Comment by Donnnno** [comment]
afbeelding
like this

**Comment by Donnnno** [comment]
Also decided to give the outlook icon a makeover because it was super outdated :s
Witch one do you like more?
afbeelding

**Comment by nonnominandus** [comment]
That new icon for teams looks great!
I would choose the second outlook option, with the extra triangle. As that seems to give it a little more playfullness.

**Comment by dkanada** [comment]
I agree that the second one looks nicer!

**Comment by Donnnno** [comment]
Thanks, I've updated the icons :)

**Comment by Donnnno** [comment]
Removed the circle in the Tiny Tiny RSS & Simple Voice Recorder and added some extra icons.

**Comment by Donnnno** [comment]
@dkanada I've added two new template options for folders & books, could be usefull, I've used these in the past already to make things consistent.
afbeelding

**Comment by Donnnno** [comment]
Fixed the issues, it should be good now.

**Pull request merged**
