### PR TITLE
Leinatan patch 1

### PR DESCRIPTION
**Pull request by Leinatan**
14 new icons (of which one is an update to slack icon) + 1 icon for simple calendar PRO version (which is the same as the non-pro version)

### CODE REVIEW

**Comment by dkanada** [comment]
Sorry for replying so late, I have had a hectic January. I will get these merged in now and then update the app on F-Droid in the next week or so. Let me know if you have any other icons to add before then!

**Comment by dkanada** [comment]
@Leinatan do you have component names for all of these icons? I just noticed you didn't include an `appfilter.xml` in the pull request.

**Comment by Leinatan** [comment]
Hey,

Thanks for the merge! I'm pretty much useless when it comes to more techincal stuff so I couldn't figure out where to/how to add this xml file. Nevertheless I added the app full names in the description of my pull request (first contribution ever so it is probably not perfect).
I'm on a trip right now and don't have access to my laptop until end of february, but I can provide infos that are accessible from my phone, such as app names.

Just tell me if they aren't visible in pull request's description !

--
Leinatan

Friday, 01 February 2019, 05:09AM -04:00 from dkanada notifications@github.com<mailto:notifications@github.com>:


@Leinatan<https://github.com/Leinatan> do you have component names for all of these icons? I just noticed you didn't include an appfilter.xml in the pull request.

**Comment by dkanada** [comment]
I just checked and I have the activity names but I really need the full component names, do you think you could install Turtl from F-Droid and send the output from that app?

**Comment by Leinatan** [comment]
Hey,

Here's Turtl's output, hope it helps:

(My Boy is missing but it's a paid app and I no longer have it....)


<item component="ComponentInfo{com.android.camera2/com.android.camera.CameraLauncher}" drawable="camera"/>

<item component="ComponentInfo{com.github.cythara/com.github.cythara.MainActivity}" drawable="cythara"/>

<item component="ComponentInfo{org.mozilla.focus/org.mozilla.focus.activity.MainActivity}" drawable="firefoxfocus"/>

<item component="ComponentInfo{com.bananadevelopment.lighthouse/md54c141cce6222f129d1b82da10b59cd89.SplashActivity}" drawable="lighthouse"/>

<item component="ComponentInfo{ch.admin.meteoswiss/ch.admin.meteoswiss.MainActivity}" drawable="meteoswiss"/>

<item component="ComponentInfo{com.my.mail/ru.mail.mailapp.SplashScreenActivity}" drawable="mymail"/>

<item component="ComponentInfo{ch.rts.rtsinfo/ch.rts.rtsinfo.MainActivity}" drawable="rtsinfo"/>

<item component="ComponentInfo{ch.sbb.mobile.android.b2c/ch.sbb.mobile.android.vnext.splashscreen.SplashScreenActivity}" drawable="sbbmobile"/>

<item component="ComponentInfo{com.automattic.simplenote/com.automattic.simplenote.NotesActivity}" drawable="simplenote"/>

<item component="ComponentInfo{com.Slack/com.Slack.ui.HomeActivity}" drawable="slack"/>

<item component="ComponentInfo{me.phh.superuser/com.koushikdutta.superuser.MainActivity}" drawable="superuser"/>

<item component="ComponentInfo{com.tf.thinkdroid.viewer.global/com.tf.thinkdroid.manager.StartActivity}" drawable="thinkfreeofficeviewer"/>

<item component="ComponentInfo{com.appxy.tinyscanner/com.appxy.tinyscanfree.Activity_Start}" drawable="tinyscanner"/>

--
Tell me if anything else is needed,

Best

Sunday, 17 February 2019, 02:03AM -05:00 from dkanada notifications@github.com<mailto:notifications@github.com>:


I just checked and I have the activity names but I really need the full component names, do you think you could install Turtl from F-Droid and send the output from that app?

**Pull request merged**
