### PR TITLE
Fixed all dark grey backgrounds and updated appfilter

### PR DESCRIPTION
**Pull request by Donnnno**

### CODE REVIEW

**Comment by dkanada** [comment]
Oops haha, I just pushed a release. I'll quickly untag it and merge this to fix the issues.

**Comment by Donnnno** [comment]
Oops I'm sorry about that :s

**Comment by dkanada** [comment]
Can you remove all the changes to `appfilter.xml` except the new icon? It's trying to add all the entries in twice now since my branch already has the changes.

**Comment by Donnnno** [comment]
Uhm Idunno how to do that quickly but the lines for the appfilter are:

```
<!-- Free Mobile Netstat -->
<item component="ComponentInfo{org.pixmob.freemobile.netstat/org.pixmob.freemobile.netstat.ui.Netstat}" drawable="freemobilenetstat"/>
```

**Comment by dkanada** [comment]
I fixed the issues directly to avoid all the merge issues. You might want to look into git branches to make pull requests easier in the future :) they let you separate commits into different sections which makes merging them easier.

Also, if you're going to add any more icons, they can't include spaces or any special characters, only normal letters. It's an Android quirk that we just have to deal with.

**Comment by Donnnno** [comment]
Thanks for the advice! and thanks for updating the pack, it's looking very sleek :-)

**Comment by dkanada** [comment]
I agree, a lot of the icons are looking really good lately!

**Pull request closed without merging**
