### PR TITLE
Simple apps

### PR DESCRIPTION
**Pull request by Swedneck**
Fixes some of #85

Calculator: com.simplemobiletools.calculator/com.simplemobiletools.calculator.activities.SplashActivity
Calendar: com.simplemobiletools.calendar/com.simplemobiletools.calendar.activities.SplashActivity
Camera: com.simplemobiletools.camera/com.simplemobiletools.camera.activities.SplashActivity
Contacts: com.simplemobiletools.contacts/com.simplemobiletools.contacts.activities.SplashActivity
Draw: com.simplemobiletools.draw/com.simplemobiletools.draw.activities.SplashActivity
File Manager: com.simplemobiletools.filemanager/com.simplemobiletools.filemanager.activities.SplashActivity
Flashlight: com.simplemobiletools.flashlight/com.simplemobiletools.flashlight.activities.SplashActivity
Gallery: com.simplemobiletools.gallery/com.simplemobiletools.gallery.activities.SplashActivity
Music Player: com.simplemobiletools.musicplayer/com.simplemobiletools.musicplayer.activities.SplashActivity
Notes: com.simplemobiletools.notes/com.simplemobiletools.notes.activities.SplashActivity

### CODE REVIEW

**Comment by dkanada** [comment]
Nice, these apps seem to be pretty popular.

**Comment by dkanada** [comment]
Do you have the component names for the clock and the launcher?

**Comment by Swedneck** [comment]
Ah, i knew i missed some!

Launcher: com.simplemobiletools.applauncher/com.simplemobiletools.applauncher.activities.SplashActivity
Clock: com.simplemobiletools.clock/com.simplemobiletools.clock.activities.SplashActivity

**Comment by dkanada** [comment]
Done!

**Pull request merged**
