### PR TITLE
Icon for Shuttle+

### PR DESCRIPTION
**Pull request by baitmooth**
created Icon for Shuttle+
solves #459

### CODE REVIEW

**Comment by Donnnno** [comment]
As for every other pull request, don't forget to add the activity names otherwise the icons won't work. It's explained in step 5 of the contributing guide:

> 5. Provide the activity names of the new apps
> 
>     These should look something like com.dkanada.icecons/com.dkanada.icecons.MainActivity
>     If you want to help even more you can add your new icons to the appfilter.xml file

Also: you don't need to make an issue for your own pull requests ;)

And you could put every icon in one pr, that would make everything more convenient for Dkanada :)

**Comment by dkanada** [comment]
@baitmooth @Donnnno is right, it will be a lot easier to review these in a single pull request. Do you think you could merge all your other icons into this one at some point?

**Comment by baitmooth** [comment]
@dkanada @Donnnno I thought that adding to appfilter.xml would be sufficient, but I will provide activity names for the icons.

I already thought about the opening issues for my icons, and decided against it for future icons. ;)

I will merge the PRs into one single branch and create a new PR. That would be better? 

Also activity names in the comment and in appfilter.xml or only in comments?

Thanks for comments and advice.

**Comment by dkanada** [comment]
I'm not sure what @Donnnno was referencing with the activity names, but your change to `appfilter.xml` here looks fine to me. That one line is all you need in a PR, plus the comment with the name which you included. I generate everything else automatically.

A single branch and pull request would be excellent, thanks :) I usually merge pull requests once a month so batching up changes is fine.

**Comment by baitmooth** [comment]
@dkanada could you check this branch i created for my icons if its good for a PR?
https://github.com/baitmooth/frost/tree/icons
should i close the remaining PRs?
And I would still add one line per Icon in the new PR. That's oK?

**Comment by baitmooth** [comment]
Closed for #472

**Pull request closed without merging**
