### PR TITLE
Some new icons and a fix

### PR DESCRIPTION
**Pull request by DanielMowitz**
I hope this is mergeable.

### CODE REVIEW

**Comment by dkanada** [comment]
I generally run the scripts for `drawable.xml` and `iconpack.xml` after a merge, along with generating the new icons myself. If you can revert those changes I'll add this to the next release.

**Comment by DanielMowitz** [comment]
The changes were reverted.

**Comment by dkanada** [comment]
I'm a bit confused, there are two icons in `other`, four in `icons`, one set of icons removed from `res` and only three additions to the `appfilter` file. Exactly which icons are new and which are changed from existing icons?

**Comment by DanielMowitz** [comment]
Ok, this was confusing for me too. The two icons in other made no sense and I do not know how they got there. The set of icons removed from res and the difference of changes in the appfilter file and the icons dir stem from one of the icons being a (hopefully) fixed version of the fruitradar svg as mentioned in #199. Sorry for the troubles with this PR.

**Comment by dkanada** [comment]
No problem at all, thanks for making so many changes!

**Pull request merged**
