### PR TITLE
4 new icons

### PR DESCRIPTION
**Pull request by h-bruch**
Added icon for Linphone
Added icon for Secuso {Foodtracker, Pedometer, ~~QR Scanner~~}
Added icon for SatStat
Added icon support for Secuso Weather
Corrected icon label for Transportr

### CODE REVIEW

**Comment by dkanada** [comment]
There is a merge issue now that I have been working through pull requests, could you fix that before I merge these?

**Comment by Donnnno** [comment]
Hi, I noticed that we both created icons for SatStat and the QR scanner.

**Comment by h-bruch** [comment]
Hello Donnnnno!
Have you made new svg's too? Couldn't find them in your branch.

**Comment by Donnnno** [comment]
Hi h-bruch,
Your SatStat icon is really nice, you should keep that one. (-:
But for consistency of the Secuso apps I would choose the round icon over the squircle one.

**Comment by h-bruch** [comment]
Hi! 
Thanks. I've just removed it. :)
Cheers!

**Pull request merged**
