### PR TITLE
add Yandex Metro icon

### PR DESCRIPTION
**Pull request by ejiek**
Icon they use upstream is for Moscow underground but this one is for Saint-Petersburg undergroud.
I guess it's fine coz they are two biggest cities in Russia and SPb is a cultural capital =]

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for all the new icons! One thing to note, Android usually needs some padding on the inside of the icon, [this](https://material.io/design/iconography/#grid-keyline-shapes) page has a good example of how large the padding should be. Otherwise these all look great.

**Comment by ejiek** [comment]
Awesome guide, thanks!

Going to update them in a couple of days

**Comment by ejiek** [comment]
Not sure if what i've done with this one is correct imolementation of the guide.

**Comment by ejiek** [comment]
I'm still in a need for piece of advice.
There are keyline shapes.
Should I shrink icons to their size?

**Comment by dkanada** [comment]
Apologies for the late response, I have been busy. The new sizes are perfect, thank you! I will merge them all now.

**Pull request merged**
