### PR TITLE
adding 21 icons 

### PR DESCRIPTION
**Pull request by suffixdesign**
i also did the appfilter.xml file.

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for the new icons! Some of them are actually already in the icon pack though, namely Simple Calculator, Chromium, Simple Gallery, and Wire. Did you want to update the old icons or are they not showing up on your phone? Is apps2sd supposed to be a solid square, and is Jota Text Editor supposed to be a wire frame icon?

Last thing to note, maybe Linux Command Library and Plumble would look better with a solid circle and the icon being in the negative space rather than a circular frame. If you want to leave them how they are I will just merge them now though.

**Comment by dkanada** [comment]
Oh, I just noticed you used the trace tool for some of these icons. Generally I try to avoid that tool because the high resolution images have wavy or jagged lines, the best way to get crisp lines is with shapes or a curve tool.

**Comment by suffixdesign** [comment]
hello dkanada!
when i started working on those 21 icons, i didn't update the iconpack beforehand, that's why i didn't notice that there are nnew additions to it. i don't want to update the icons, they are fine as there is.apps2sd: it's supposed to be an android with a wrench on a microsd card, but i had to make some compromise to make it minimal but unique.
jota: the same as above, also it's a notepad with a pencil.
linuxcommanlib and plumble: it's your iconpack, i'm just contributing into it. the final decision as to what will look better is yours to make. if you think it'll look better that way, just change it. i'll not be angry or pissed about it.
kind regards:
b.

-- Eredeti üzenet --
Feladó: dkanada&lt;notifications@github.com&gt;Címzett: dkanada/frost&lt;frost@noreply.github.com&gt;Elküldve: 2018. november 4. 17:2Tárgy : Re: [dkanada/frost] adding 21 icons  (#123)


Thanks for the new icons! Some of them are actually already in the icon pack though, namely Simple Calculator, Chromium, Simple Gallery, and Wire. Did you want to update the old icons or are they not showing up on your phone? Is apps2sd supposed to be a solid square, and is Jota Text Editor supposed to be a wire frame icon?
Last thing to note, maybe Linux Command Library and Plumble would look better with a solid circle and the icon being in the negative space rather than a circular frame. If you want to leave them how they are I will just merge them now though.

**Comment by suffixdesign** [comment]
hi again!
i'm no vector guy, i started working with deluxe paint, then paint shop pro, the photoshop. i'm just skimming the surface of adobe illustrator (what i used for autotracing), and believe me, i tried to play with the sliders to my best intent, but they never got so efficient as your svgs. i mean, 234 bytes for an afwall icon? come on, that's cheating.

so, i don't know how to trace efficiently, nor i know how to use the curve tool. as for the shapes, that's too much hassle for me to recreate an apps icon in a creation platform i know almost nothing about. i tried to bridge the gap by using photoshop's vector tools, but the filesizes kept growing, and growing.
on a different matter, can i suggest some wallpaper additions? the default ones (which were included with icecons, too) are too bland for my taste.

b.

-------------------------------------

-- Eredeti üzenet --
Feladó: dkanada&lt;notifications@github.com&gt;Címzett: dkanada/frost&lt;frost@noreply.github.com&gt;Elküldve: 2018. november 5. 12:33Tárgy : Re: [dkanada/frost] adding 21 icons  (#123)


Oh, I just noticed you used the trace tool for some of these icons . Generally I try to avoid that tool because the high resolution images have wavy or jagged lines, the best way to get crisp lines is with shapes or a curve tool.

**Comment by dkanada** [comment]
Sounds good! I will make a couple changes to see if I can reduce the file sizes :) and also fix the duplicate icons. For the wallpaper suggestions, it depends on what license they have. What did you have in mind?

**Comment by dkanada** [comment]
All of those photos look nice but I don't think I will include them in the app. Right now the app size is already 40MB, a lot of which I think is used by the twelve wallpapers currently in the app, so adding any more would only make the size worse.

**Comment by suffixdesign** [comment]
okay, and how about replacing the similars from the original twelve with from of my suggestions? i din't meant to include all of them anyways. 

b .

-- Eredeti üzenet --
Feladó: dkanada&lt;notifications@github.com&gt;Címzett: dkanada/frost&lt;frost@noreply.github.com&gt;Elküldve: 2018. november 7. 18:58Tárgy : Re: [dkanada/frost] adding 21 icons  (#123)


All of those photos look nice but I don't think I will include them in the app. Right now the app size is already 40MB, a lot of which I think is used by the twelve wallpapers currently in the app, so adding any more would only make the size worse.

**Pull request merged**
