### PR TITLE
Add five icons

### PR DESCRIPTION
**Pull request by Rudertier**
Hi,
thanks for the nice set of icons. I added five icons really quick.
For _flinkster_ and _callabike_ I modified the _dbnavigator_ icon.
For _sonos_ I reproduced the official sonos icon by vectorising their logo.
For _feeder_ I vectorised the official feeder icon, which I also did for _pocket_.

Can you tell me how to provide the activity names?

Best!

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for the new icons! You can find the activity names with the app Turtl on F-Droid, it can produce a zip file or copy the relevant data to the clipboard. Then just copy the result into a text file in the **other** directory and I can handle the rest. If you use the zip option I only need the appfilter.xml file, none of the icons.

**Comment by Rudertier** [comment]
Hi,
F-Droid is unwilling to install this app on my phone. Complaining, that a version of turtl with another key is already installed. Which I never did. Is there a way to work around turtl, or should I solve this problem first?

**Comment by dkanada** [comment]
You can technically use any app to get the package name and class name with Category.LAUNCHER to manually create the component names, but the easiest way is just to use an app like Turtl that generates them for you.

The F-Droid issue can be fixed by resetting the app data and cache if I recall correctly. I also noticed that building F-Droid from the current master branch seems to fix that issue, so hopefully it won't be a problem after the next update. The newer icons look good too by the way.

**Comment by dkanada** [comment]
Good to go! You can check my last couple commits if you want to know where I included that information for next time, I use scripts to automate a lot of the work. I will push an update to F-Droid shortly.

**Pull request merged**
