### PR TITLE
New icons, activities, and script tweaks

### PR DESCRIPTION
**Pull request by ohemelaar**
- Closes issues #141 and #140
- Tweak `white.sh` to be able to handle more SVGs 
- Add icons for:
  - Generic Bus
  - Credit Agricole
  - Freebox Compagnon
  - N26 Bank
  - Tisseo
  - Trainline.eu
  - Deluge client
  - DeTeXify
  - devRant
  - Duolingo
  - Meetup
  - Shrug keyboard
  - Bike rental location service
  - Fuel flash
  - Recycling information
  - Slack

### CODE REVIEW

**Comment by dkanada** [comment]
These look great! A few notes, the `tisseo` and `shrug` icons will probably be really hard to see when viewed from a phone, could you maybe simplify and enlarge the strokes a bit? Also, you can just choose your favorite for the square and circle icon shapes, this icon pack doesn't really have support for different shapes so I'd rather just keep one icon per app to keep the size down.

**Comment by ohemelaar** [comment]
Thanks for the feedback. I tried to mimic the original icons, but I'll look for alternatives.
Also, I'll keep the circle ones (the ones that are referenced into `appfilter.xml`.
tisso
shrug

**Comment by dkanada** [comment]
Yeah, your icons are basically pixel perfect recreations haha, definitely better than I could do in Inkscape :) I just wanted to mention that you can modify the icons a little to fit the style of the rest of the icon pack if you want. I made changes to the F-Droid and Camera icons to make them super simple as an example.

**Comment by dkanada** [comment]
I will merge for now because the icons look great, and then in the future if you want you can change the two above =p they're probably fine. I will push a release soon to get this updated.

**Comment by ohemelaar** [comment]
I'll definitely do this, I have some more icons I want to draw too, but it'll have to wait a month or two :)

**Pull request merged**
