### PR TITLE
Add SVGs for Issue #327

### PR DESCRIPTION
**Pull request by Saijin-Naib**
Add two SVGs for my Issue #327 

Best Buy
com.bestbuy.android/com.bestbuy

Bing
com.microsoft.bing/com.microsoft.clients.bing

Hopefully I did this correctly. First time really doing anything of consequence with InkScape.

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Add SVG for Gitter IM
im.gitter.gitter/im.gitter.gitter

**Comment by Saijin-Naib** [comment]
Add SVG for Collabora Office
com.collabora.libreoffice/org.libreoffice

**Comment by Saijin-Naib** [comment]
Add SVG for Dronecast
com.droneforecast.app/com.droneforecast

**Comment by Saijin-Naib** [comment]
Add SVG for TrailSense
com.kylecorry.trail_sense/com.kylecorry.trail_sense

**Comment by Saijin-Naib** [comment]
Add SVG for myCricKet
com.mizmowireless.acctmgt/com.streamezzo

**Comment by z4-xz** [comment]
Instead of saving your Inkscape project as a Inkscape svg, just pick plain svg from dropdown list. Your files will look cleaner :)))

**Comment by Saijin-Naib** [comment]
> Instead of saving your Inkscape project as a Inkscape svg, just pick plain svg from dropdown list. Your files will look cleaner :)))

What is the implication for the file itself?

**Comment by Saijin-Naib** [comment]
As per @z4-xz , I've re-saved all the submitted SVGs as Plain SVG, which apparently is a much simpler format/schema than the InkScape SVG.

Thanks for the tip!

**Comment by Saijin-Naib** [comment]
Add SVG for Microsoft To-Do
com.microsoft.todos/com.microsoft.todos

**Comment by Saijin-Naib** [comment]
I think this, if it passes review, can be merged. I'm at the point where the remainder of the logos I have requested have some combination of font/text, curves, and/or graphics, and that is way, way beyond my capabilities with vector art at the moment.

**Comment by Saijin-Naib** [comment]
Add SVG For ActiveBuilding
com.activebuilding.residents/com.activebuilding.residents

**Comment by dkanada** [comment]
Thanks for all these icons!

**Comment by dkanada** [comment]
I'll add them soon, I have to update the appfilter file to make sure these are picked up first.

**Comment by Saijin-Naib** [comment]
Thanks so much! 

I will study what you do with that appfilter so I understand that part properly for next time.

If I may ask, can Frost skin "action" icons, like the home/work ones from Magic Earth?

**Comment by dkanada** [comment]
Technically it can't do anything, it follows an ancient standard made back when custom launchers were first popping up on the Play Store. I forget which app made the specification (or even where you can find it online) but you can always check if action buttons are supported. There are actually some other cool stuff you can theme as well, I just haven't been interested in supporting them.

**Comment by Saijin-Naib** [comment]
Missed fixing Bing and BestBuy SVGs before. They're now Plain SVGs, and the embedded PNG logos have been removed (whoops!)

**Pull request closed without merging**
