### PR TITLE
Added 2 icons and redone 1 icon

### PR DESCRIPTION
**Pull request by Leinatan**
For some reason the Viseca One icon I submitted last time didn't go through the last update, so I'm trying again. I modified it so it respects the square template as well. Thanks!
Activity names in the icons.txt file

### CODE REVIEW

**Comment by dkanada** [comment]
It looks like the issue was that I added the Viseca One icon with a different name, I can fix that up for the next release. The icon is causing a merge issue though, could you remove it from this pull request?

**Comment by dkanada** [comment]
It actually looks like your fork is very outdated, which is causing the merge issues. They should get fixed if you just recreate the fork from master and then add the two new icons in a commit.

**Comment by dkanada** [comment]
I fixed the VisecaOne icon and added the Turtl icon in a commit just now since I plan on tagging a release tonight. The SwissCom icon wasn't made by hand so I didn't add it with the Turtl icon. The generated icons are generally a pain to deal with so I don't include them.

**Comment by Leinatan** [comment]
Ok, so be it! Sorry I really don't have much time for this these days ;)

**Pull request closed without merging**
