### PR TITLE
Clean out some unnecessary shapes

### PR DESCRIPTION
**Pull request by ejiek**
Addresses #264.
Already converted a buch of them. The only thing left is to clean up after inkscape.

@dkanada should i put them in `other` or it's ok to leave them in `icons`?

### CODE REVIEW

**Comment by dkanada** [comment]
Please move them to `other` so I can easily run the script only on the new icons :) otherwise it takes quite a while with the entire list.

**Comment by ejiek** [comment]
Not sure what to do with `appleflinger.svg` just going to leave it as is for now

**Comment by Donnnno** [comment]
Quite a radical change! Did you keep the icon balance in mind when converting them? Or do they all have the same length or width now?
Artboard 1

**Comment by ejiek** [comment]
@Donnnno not really. It's kind of a rule for icons "background" so I'm not sure how to apply it.

Right now all of them are limited by 44px in width or hight whichever happens to be bigger.
This was rather bald move and I'm more than open to more elegant ideas =]

**Comment by ejiek** [comment]
I've understood that covering whole repo in one go is too much for me =]

**Comment by Donnnno** [comment]
Cool! I'm curious how it turns out. :)

**Comment by dkanada** [comment]
Proper sizing can definitely be a challenge. Sometimes you even have to move the icon off center depending on the weight of the shape. Arrows look best when their center of gravity is used rather than their bounding edges, and trapezoids require a shift in the direction of their narrow edge. These all look extremely good though!

**Comment by dkanada** [comment]
Another annoying rule is that the less circular an icon gets, the larger is will have to be to overcome the regular size limits. Nextcloud and Jitsi will probably look best at around 46 pixels since they're so narrow on one dimension.

**Comment by dkanada** [comment]
Wow this one will take a while to look through, so many changes!

**Comment by ejiek** [comment]
Thanks for the review!

In my opinion it's absolutely fine not to accept all of the converted icons (but it's much easier to decline them when you can compare converted version with a regular one).
I'll try to address at least sizes this weekend!

**Comment by dkanada** [comment]
The sizes still seem to be broken on GitHub, maybe it needs to be compared to existing files? I'm referring to the "rich diff" mofe that lets you view the actual icons online, so I don't have to download each one individually and compare it to the old files. You can view the icon but it's the size of a fingernail on my screen instead of 10-20cm like most of the other ones.

**Comment by ejiek** [comment]
I've missed this varian because qutebrowser renders it in a couple of pixels but firefox seems to be just fine.

**Comment by dkanada** [comment]
I was just about to switch back to Qutebrowser! Such a good program, I temporarily moved to Firefox again for extensions but it's not worth it.

**Pull request merged**
