### PR TITLE
Added More Icons

### PR DESCRIPTION
**Pull request by nonnominandus**
I made the necessary icons and changes for request #242.
preview
I created icons for 4 apps from FDroid still missing an icon (and looking like such on my phone). Added an extra name for Mindustry (also FDroid). And I created an icon for floatplane.
preview2
For the icon for UnCiv I choose to use the lower icon (from the two options) as this one is I think more in line with the style of the iconpack and looks cleaner. The two options are both added as seperate files if somebody wants to do something with them (can be deleted if not used in the iconpack).

### CODE REVIEW

**Comment by dkanada** [comment]
These look great! My only suggestions would be remove the shadow and little accent thing from the center tile in Open Sudoku, remove the words from Die Techniker and center the inner shape, and maybe drop the outer circle for NebandeDe.

**Comment by nonnominandus** [comment]
I did the things you proposed. I agree with them this ways it looks better. Also I removed the variants of UnCiv as these will not be used anymore.
preview3

**Comment by nonnominandus** [comment]
I made 5 more.
preview
Some microsoft apps and an FDroid one.

**Comment by TobiasDev** [comment]
Cant wait for these icons! :)

**Comment by nonnominandus** [comment]
preview4
I created 10 more icons and added another activity name.
These were the last icons missing on my device so some are somewhat more regional, but there is one FDroid icon in there.

**Comment by nonnominandus** [comment]
I added the extra activity name as requested in #244.

**Comment by TobiasDev** [comment]
Any chance of seeing this in the next F-Droid update? :)

**Comment by nonnominandus** [comment]
I would hope so, but I have not seen @dkana, I guess he will merge it on his own time.

**Comment by dkanada** [comment]
This pull request had just missed the last update. I usually update about once a month so not too long now, sorry for the wait.

**Comment by nonnominandus** [comment]
It's fine it was just a bit silent from your side so I had nothing to go on. Especially nothing regarding if you deemed my additions 'worthy' ;-). But it's fine.

**Comment by Donnnno** [comment]
Hi, I made some really small adjustments to the office icons, the heights of the characters are now exactly even. And there are some rounded corner & other tweaks.
afbeelding

I've added them in this zip:
[office.zip](https://github.com/dkanada/frost/files/4167169/office.zip)

**Comment by nonnominandus** [comment]
Nice work! I always seem to stick a little to close to the original logo. This veriants look much cleaner.

**Comment by Donnnno** [comment]
Thanks, I always try to find a balance between the original and how it looks when it's flat. The original icons (with depth/3d effects) are really well designed in that context, but when you flatten it, it kinda looks weird if you don't make any adjustments to it.
Everything else looks great btw :)

**Comment by nonnominandus** [comment]
I totally agree! Thanks!

**Pull request merged**
