### PR TITLE
added icons 

### PR DESCRIPTION
**Pull request by MarcSN311**
for CuprumPDF, DiskUsage, Napster, Nextcloud, NextcloudSMS, Notizen, SecScanQR, Tasker, TitaniumBackup

### CODE REVIEW

**Comment by MarcSN311** [comment]
done!

**Comment by dkanada** [comment]
Thanks! Feel free to submit other icons whenever you like, I generally make a couple each month and make sure to keep F-Droid updated whenever a new PR is made.

**Comment by dkanada** [comment]
I noticed before I pushed a new version that these icons were probably drawn by hand or converted automatically with a tool. Icons created this way generally look much worse at higher resolutions so I usually don't accept them unless the shape is extremely complicated. Since I already merged these ones and I had some spare time I redrew these again using shapes and other tools in Inkscape.

**Comment by MarcSN311** [comment]
Sorry about that! I never did anything like that before, so I drew them in photoshop and converted them in Inkscape. I'll watch some videos on inkscape before creating the next icons.

**Comment by dkanada** [comment]
Ah okay, no worries :) Let me know if you have any questions!

**Pull request merged**
