### PR TITLE
New images

### PR DESCRIPTION
**Pull request by Donnnno**
Created new images for the featureImage, Header and example list.

### CODE REVIEW

**Comment by dkanada** [comment]
I only see a new file for `header-background` but your branch is also starting to diverge a lot from my repository. What tools are you using for git? I can explain how to set up branches for pull requests to fix the issue.

**Comment by Donnnno** [comment]
Hi, I started using github desktop and gitbash since the last frost update. But it was unclear for me how to sync my master with yours.

**Comment by dkanada** [comment]
The easiest way to keep your repository synced is to use a new branch for each pull request and then just delete the branch when you finish. I'm not sure you can easily fix your current fork of this repository though, so I would suggest deleting and reforking to fix the current issues. I looked up GitHub Desktop and you can create a new branch based on [step four](https://www.attosol.com/create-and-merge-branches-using-github-desktop-client/) in that link.

It looks like GitHub Desktop doesn't support syncing with upstream which is the best way to update the master branch, but as long as you never touch the master branch and always create a new branch there shouldn't be any merge conflicts. Then when you create a pull request, just use the new branch instead of master when you submit the changes.

**Comment by dkanada** [comment]
If that sounds like a lot of work you could also just never remove any images or make any changes to your branch besides new additions, that should also avoid merge issues. They only happen when you start adding commits that I can't merge to master, like removing items I have already merged and removed on my branch.

You could also do whatever you want on your branch and I will just merge the delta changes (squash merge) but ignore your commit history, but then you don't get as much credit on my branch so I like to avoid that when possible.

**Comment by Donnnno** [comment]
Thanks for the advise, I'll create a new fork then. I already started using branches so I hope it works now.

**Pull request closed without merging**
