### PR TITLE
issue #255 - added icons

### PR DESCRIPTION
**Pull request by karrb**
Adding 
- My Expenses
- NordVpn
- pCloud
- Track Work Time

I would like to test locally if there are steps to using the tools in other?

### CODE REVIEW

**Comment by dkanada** [comment]
Sure, I run `raster.sh` to automatically add all icons in `other` to the project, and then `xml.sh` to include them in some required files. That should be all you need to test this locally.

**Comment by karrb** [comment]
> Sure, I run `raster.sh` to automatically add all icons in `other` to the project, and then `xml.sh` to include them in some required files. That should be all you need to test this locally.

Okay cool, I will look into that. I added them manually for the time being

**Comment by dkanada** [comment]
I actually run the scripts after merging pull requests, so if you could remove the assets themselves and just leave the SVG files in `other` I can take care of the rest.

**Comment by karrb** [comment]
Sure, I will work on that tonight. I have been busy working on a few other projects. I also have a bunch of icons that I have added in a different branch. Once this one goes through I will do another pull request :smile:

**Comment by karrb** [comment]
> I actually run the scripts after merging pull requests, so if you could remove the assets themselves and just leave the SVG files in `other` I can take care of the rest.

I think this done down

**Pull request merged**
