### PR TITLE
39 new icons

### PR DESCRIPTION
**Pull request by Donnnno**
Hi, I'm new to all this so I hope this goes well...

I've created icons for the following apps:

- Bromite - org.bromite.bromite
- Firefox Send - org.mozilla.firefoxsend
- Firefox Preview - org.mozilla.fenix
- Pocketcasts - au.com.shiftyjelly.pocketcasts
- Trebleshot - com.genonbeta.TrebleShot
- Blokada - org.blokada.alarm
- My Avans - nl.brianvdbroek.avansapp
- Transportr - de.grobox.liberario
- Binary Eye - de.markusfisch.android.binaryeye
- NOS - nl.nos.app

### CODE REVIEW

**Comment by Donnnno** [comment]
Added 10 extra icons

- Firefox Notes - org.mozilla.testpilot.notes
-     Simple Last.fm Scrobbler - com.adam.aslfms/com.adam.aslfms.SettingsActivity
-     News - de.luhmer.owncloudnewsreader/de.luhmer.owncloudnewsreader.NewsReaderListActivity
-     WebApps - com.tobykurien.webapps/com.tobykurien.webapps.activity.MainActivity
-     SkyTube - free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity
-     Simple Solitaire Collection - de.tobiasbielefeld.solitaire/de.tobiasbielefeld.solitaire.ui.GameSelector
-     Koler - com.chooloo.www.callmanager
-     Pdf Viewer Plus - com.gsnathan.pdfviewer
-     Ticketswap - com.ticketswap.ticketswap

updated icon for Twidere - org.mariotaku.twidere

**Comment by Donnnno** [comment]
10 more new icons, 
I've remade the Aurora Store icon to be more fitting with the Aurora Droid one.

- 5th Edition Spellbook - com.spellsdd5
- ActionDash - com.actiondash.playstore
- Action Launcher - com.actionlauncher.playstore
- Aurora Droid - com.aurora.android
- Aurora Store - com.aurora.store
- Bankieren - nl.asnbank.asnbankieren
- Fedilab - fr.gouv.etalab.mastodon
- Minesweeper - org.secuso.privacyfriendlyminesweeper
- Openscale - com.health.openscale
- Sudoku - org.secuso.privacyfriendlysudoku

**Comment by dkanada** [comment]
These all look really great! I'll actually need the full ComponentName to get them all added though. If you have all these apps installed you can easily grab them all by running a scan with Turtl and pasting the result here.

Two minor issues with the icons. I noticed the first one had a jagged edge in the bottom right, if that's intentional then you can ignore this comment. You also left grey rectangles in several of the finished icons, it would be helpful if you could remove them.

**Comment by Donnnno** [comment]
Thanks! The grey backgrounds should be removed now, but what icon had a jagged edge? I don't see it :s 

I'll gather the ComponentNames later today.

**Comment by Donnnno** [comment]
These should be all of them.


<item component="ComponentInfo{com.spellsdd5/com.spelldd5.MainActivity}" drawable="5theditionspellbook"/>

<item component="ComponentInfo{com.actionlauncher.playstore/com.actionlauncher.ActionLauncherActivity}" drawable="actionlauncher"/>

<item component="ComponentInfo{com.actiondash.playstore/actiondash.MainActivity}" drawable="actiondash"/>

<item component="ComponentInfo{com.aurora.adroid/com.aurora.adroid.activity.AuroraActivity}" drawable="auroradroid"/>

<item component="ComponentInfo{com.aurora.store/com.aurora.store.activity.AuroraActivity}" drawable="aurorastore"/>

<item component="ComponentInfo{nl.asnbank.asnbankieren/com.service2media.m2active.client.android.M2ActiveClient}" drawable="bankieren"/>

<item component="ComponentInfo{de.markusfisch.android.binaryeye/de.markusfisch.android.binaryeye.activity.SplashActivity}" drawable="binaryeye"/>

<item component="ComponentInfo{org.blokada.alarm/core.MainActivity}" drawable="blokada"/>

<item component="ComponentInfo{org.bromite.bromite/com.google.android.apps.chrome.Main}" drawable="bromite"/>

<item component="ComponentInfo{fr.gouv.etalab.mastodon/app.fedilab.android.activities.MainActivity}" drawable="fedilab"/>

<item component="ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}" drawable="firefoxpreview"/>

<item component="ComponentInfo{com.chooloo.www.callmanager/com.chooloo.www.callmanager.ui.activity.MainActivity}" drawable="koler"/>

<item component="ComponentInfo{org.secuso.privacyfriendlyminesweeper/org.secuso.privacyfriendlyminesweeper.activities.SplashActivity}" drawable="minesweeper"/>

<item component="ComponentInfo{nl.brianvdbroek.avansapp/nl.brianvdbroek.avansapp.MainActivity}" drawable="myavans"/>

<item component="ComponentInfo{de.luhmer.owncloudnewsreader/de.luhmer.owncloudnewsreader.NewsReaderListActivity}" drawable="news"/>

<item component="ComponentInfo{nl.nos.app/nl.nos.app.activity.SplashActivity}" drawable="nos"/>

<item component="ComponentInfo{org.mozilla.testpilot.notes/org.mozilla.testpilot.notes.MainActivity}" drawable="notes"/>

<item component="ComponentInfo{com.health.openscale/com.health.openscale.gui.MainActivity}" drawable="openscale"/>

<item component="ComponentInfo{com.gsnathan.pdfviewer/com.gsnathan.pdfviewer.MainActivity_}" drawable="pdfviewerplus"/>

<item component="ComponentInfo{au.com.shiftyjelly.pocketcasts/au.com.shiftyjelly.pocketcasts.ui.MainActivity}" drawable="pocketcasts"/>

<item component="ComponentInfo{org.mozilla.firefoxsend/org.mozilla.firefoxsend.MainActivity}" drawable="send"/>

<item component="ComponentInfo{com.adam.aslfms/com.adam.aslfms.SettingsActivity}" drawable="simplelast.fmscrobbler"/>

<item component="ComponentInfo{de.tobiasbielefeld.solitaire/de.tobiasbielefeld.solitaire.ui.GameSelector}" drawable="simplesolitairecollection"/>

<item component="ComponentInfo{free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity}" drawable="skytube"/>

<item component="ComponentInfo{org.secuso.privacyfriendlysudoku/org.secuso.privacyfriendlysudoku.ui.SplashActivity}" drawable="sudoku"/>

<item component="ComponentInfo{com.ticketswap.ticketswap/com.ticketswap.android.ui.LauncherActivity}" drawable="ticketswap"/>

<item component="ComponentInfo{de.grobox.liberario/de.grobox.transportr.map.MapActivity}" drawable="transportr"/>

<item component="ComponentInfo{com.genonbeta.TrebleShot/com.genonbeta.TrebleShot.activity.HomeActivity}" drawable="trebleshot"/>

<item component="ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.MainActivity}" drawable="twidere"/>

<item component="ComponentInfo{com.tobykurien.webapps/com.tobykurien.webapps.activity.MainActivity}" drawable="webapps"/>

**Comment by Donnnno** [comment]
These should be all of them.
```
<!-- 5th Edition Spellbook -->
<item component="ComponentInfo{com.spellsdd5/com.spelldd5.MainActivity}" drawable="5theditionspellbook"/>
<!-- Action Launcher -->
<item component="ComponentInfo{com.actionlauncher.playstore/com.actionlauncher.ActionLauncherActivity}" drawable="actionlauncher"/>
<!-- ActionDash -->
<item component="ComponentInfo{com.actiondash.playstore/actiondash.MainActivity}" drawable="actiondash"/>
<!-- Aurora Droid -->
<item component="ComponentInfo{com.aurora.adroid/com.aurora.adroid.activity.AuroraActivity}" drawable="auroradroid"/>
<!-- Aurora Store -->
<item component="ComponentInfo{com.aurora.store/com.aurora.store.activity.AuroraActivity}" drawable="aurorastore"/>
<!-- Bankieren -->
<item component="ComponentInfo{nl.asnbank.asnbankieren/com.service2media.m2active.client.android.M2ActiveClient}" drawable="bankieren"/>
<!-- Binary Eye -->
<item component="ComponentInfo{de.markusfisch.android.binaryeye/de.markusfisch.android.binaryeye.activity.SplashActivity}" drawable="binaryeye"/>
<!-- Blokada -->
<item component="ComponentInfo{org.blokada.alarm/core.MainActivity}" drawable="blokada"/>
<!-- Bromite -->
<item component="ComponentInfo{org.bromite.bromite/com.google.android.apps.chrome.Main}" drawable="bromite"/>
<!-- Fedilab -->
<item component="ComponentInfo{fr.gouv.etalab.mastodon/app.fedilab.android.activities.MainActivity}" drawable="fedilab"/>
<!-- Firefox Preview -->
<item component="ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}" drawable="firefoxpreview"/>
<!-- Koler -->
<item component="ComponentInfo{com.chooloo.www.callmanager/com.chooloo.www.callmanager.ui.activity.MainActivity}" drawable="koler"/>
<!-- Minesweeper -->
<item component="ComponentInfo{org.secuso.privacyfriendlyminesweeper/org.secuso.privacyfriendlyminesweeper.activities.SplashActivity}" drawable="minesweeper"/>
<!-- My Avans -->
<item component="ComponentInfo{nl.brianvdbroek.avansapp/nl.brianvdbroek.avansapp.MainActivity}" drawable="myavans"/>
<!-- News -->
<item component="ComponentInfo{de.luhmer.owncloudnewsreader/de.luhmer.owncloudnewsreader.NewsReaderListActivity}" drawable="news"/>
<!-- NOS -->
<item component="ComponentInfo{nl.nos.app/nl.nos.app.activity.SplashActivity}" drawable="nos"/>
<!-- Notes -->
<item component="ComponentInfo{org.mozilla.testpilot.notes/org.mozilla.testpilot.notes.MainActivity}" drawable="notes"/>
<!-- openScale -->
<item component="ComponentInfo{com.health.openscale/com.health.openscale.gui.MainActivity}" drawable="openscale"/>
<!-- Pdf Viewer Plus -->
<item component="ComponentInfo{com.gsnathan.pdfviewer/com.gsnathan.pdfviewer.MainActivity_}" drawable="pdfviewerplus"/>
<!-- Pocket Casts -->
<item component="ComponentInfo{au.com.shiftyjelly.pocketcasts/au.com.shiftyjelly.pocketcasts.ui.MainActivity}" drawable="pocketcasts"/>
<!-- Send -->
<item component="ComponentInfo{org.mozilla.firefoxsend/org.mozilla.firefoxsend.MainActivity}" drawable="send"/>
<!-- Simple Last.fm Scrobbler -->
<item component="ComponentInfo{com.adam.aslfms/com.adam.aslfms.SettingsActivity}" drawable="simplelast.fmscrobbler"/>
<!-- Simple Solitaire Collection -->
<item component="ComponentInfo{de.tobiasbielefeld.solitaire/de.tobiasbielefeld.solitaire.ui.GameSelector}" drawable="simplesolitairecollection"/>
<!-- SkyTube -->
<item component="ComponentInfo{free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity}" drawable="skytube"/>
<!-- Sudoku -->
<item component="ComponentInfo{org.secuso.privacyfriendlysudoku/org.secuso.privacyfriendlysudoku.ui.SplashActivity}" drawable="sudoku"/>
<!-- TicketSwap -->
<item component="ComponentInfo{com.ticketswap.ticketswap/com.ticketswap.android.ui.LauncherActivity}" drawable="ticketswap"/>
<!-- Transportr -->
<item component="ComponentInfo{de.grobox.liberario/de.grobox.transportr.map.MapActivity}" drawable="transportr"/>
<!-- TrebleShot -->
<item component="ComponentInfo{com.genonbeta.TrebleShot/com.genonbeta.TrebleShot.activity.HomeActivity}" drawable="trebleshot"/>
<!-- Twidere -->
<item component="ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.MainActivity}" drawable="twidere"/>
<!-- WebApps -->
<item component="ComponentInfo{com.tobykurien.webapps/com.tobykurien.webapps.activity.MainActivity}" drawable="webapps"/>
```

**Comment by dkanada** [comment]
The very first icon related to a spellbook seems to have a jagged edge in the bottom right, if that's intentional I can leave it though.

**Comment by Donnnno** [comment]
Hi, the spellbook icon is fixed now, there was a weird bug with exporting or something. It should be fixed now (:

**Comment by dkanada** [comment]
It looks like there were twelve icons without any additions to the `appfilter.xml` file. I left them in the other folder, any chance you could open a PR to add those component names to the file?

**Comment by Donnnno** [comment]
Oh yea, I forgot. It's fixed now :)

**Pull request merged**
