### PR TITLE
Added some icons

### PR DESCRIPTION
**Pull request by nonnominandus**
overview
I added some icons of my own (including somee more localised to the Netherlands) and solved two icon requests (#69 and #210). See the image for more details and a sneak peak.

### CODE REVIEW

**Comment by dkanada** [comment]
This is a minor issue, but FBReader and PassAndroid have very small lines which I generally try to avoid with this icon pack as a style. If I add any gaps they will usually look more like your Kodi Remote icon :)

That corner fold thing is not standardized in this icon pack either. If you have any thoughts on the best style feel free to comment. Sometimes icons just remove the corner and other times they include the gap. It's a similar issue though, since the corner fold usually has smaller gaps, so I have avoided the problem until now :smile:

**Comment by dkanada** [comment]
@nonnominandus did you find the time to make any changes?

**Comment by nonnominandus** [comment]
I had a lot to finish with my bachelors thesis, so not yet. But I planned to change it soon.

**Comment by nonnominandus** [comment]
Preview_frost_additional_changes
I updated the style of the icons you pointed out, and additionally used the folded corner of the gsuite icons to have a little bit more coherence in all icons.
I am not yet very familiar to how this now will work, but I mentioned this pull request in my commit so that commit is visible above. If any other input from me is necessary to include the new icons in this pull request I would like to hear.

**Comment by dkanada** [comment]
Those new changes look great! It looks like you removed two files in the pull request though, was that intentional?

**Comment by nonnominandus** [comment]
I deleted the icons I added in the last pull request from the directory in which new icons should be added. So those icons now should be in de main icons folder.

**Pull request merged**
