### PR TITLE
add simplemobiletools voicerecorder

### PR DESCRIPTION
**Pull request by braniii**
Here the appfilters for simplemobiletools voicerecorder app. The icon is missing, sorry for that.

### CODE REVIEW

**Comment by Donnnno** [comment]
Hey I've added this pull request to mine with an icon: #293 
Thanks!

**Comment by dkanada** [comment]
@Donnnno do you mean I shouldn't merge this one or that I need to merge it before yours?

**Comment by Donnnno** [comment]
You don't need to merge this one. I've applied this code already with my pull request :)

**Comment by braniii** [comment]
So I guess I can close this one.

**Comment by dkanada** [comment]
@braniii thanks for the changes though! Feel free to add anything in the future. :smile:

**Pull request closed without merging**
