### PR TITLE
YouTube Music icon

### PR DESCRIPTION
**Pull request by Gnorv**
I downloaded the YouTube Music logo svg file from Wikimedia (https://commons.wikimedia.org/wiki/File:Youtube_Music_logo.svg), changed it's colours and uploaded it here. It is under public domain so there should be no copyright problems.

It is supposed to be for the app "YouTube Music" ( com.google.android.apps.youtube.music ).

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, your icon is black now, can you make it white? Otherwise, it will not end up in the icon pack

**Comment by Gnorv** [comment]
Yes, sorry. I botched that one. Is it okay to just upload it here as a comment or should I revoke the Pull request and change it in my /other ? Sorry, quite unexperienced in working with GitHub.
[Youtube_Music_logo_frost.zip](https://github.com/dkanada/frost/files/5371155/Youtube_Music_logo_frost.zip)

**Comment by dkanada** [comment]
The icon also needs some padding as suggested by the Material Design documentation for Android. I think circles require 4dp of padding but I'd have to check.

**Comment by Donnnno** [comment]
> 
> 
> The icon also needs some padding as suggested by the Material Design documentation for Android. I think circles require 4dp of padding but I'd have to check.

4 dp indeed 
(docsize = 48px, circle shape = 44px)

**Comment by Gnorv** [comment]
I do not know what you mean by padding. I would do as requested but I am not sure I understand.

**Comment by Donnnno** [comment]
I think it's better to leave an icon request in the issues tab instead of a pull request 🙃 
Also can you follow the steps provided in the read me?

**Comment by dkanada** [comment]
I can't merge this one without padding, but if someone else makes the change I'd be happy to add this icon in the next release.

**Pull request closed without merging**
