### PR TITLE
Additional logos

### PR DESCRIPTION
**Pull request by ArsenyZorin**
Adds 8 new logos:

* Airbnb
* Aviasales
* Equalizer (Syberia OS)
* IVI (Russian streaming service)
* Kinoteatr (Russian cinema tickets selling service)
* Megafon (Russian carrier)
* Stocard
* Yandex.Weather

Also uses camera logo for Syberia OS camera app.

### CODE REVIEW

**Comment by dkanada** [comment]
My version of Inkscape can't parse your svg files in either PR for some reason. Any chance you could use the unmodified svg files with all the metadata? I have a script that will strip them down once they get added to the main folder.

**Comment by ArsenyZorin** [comment]
Hello. I've commited unmodified svg with metadata from inkscape. Hope it will help

**Comment by ArsenyZorin** [comment]
UPD:
Adds two new logos.
* SeriesGuide
* CarSmile - Russian Car Sharing service

**Comment by dkanada** [comment]
thanks for all the new icons :)

**Pull request merged**
