### PR TITLE
update Magisk Manager app info and icon

### PR DESCRIPTION
**Pull request by ejiek**
Not sure if it's a good idea to delete old app info in appfilter (compatibility sake).

Created a new i've coz haven't seen the old one.

### CODE REVIEW

**Comment by dkanada** [comment]
I usually leave them just in case. If you use Magisk Hide there probably isn't a way to get this working though, because I think it works by renaming the file randomly, which means the launcher will always think it's a new app.

**Comment by ejiek** [comment]
Thanks for the advice!

Looks a lot like Hide option, my bad =\

**Comment by ArsenyZorin** [comment]
@dkanada It seems that it's not Magisk Hide. I have the same name
```
ComponentInfo{com.topjohnwu.magisk/a.c}
```

**Comment by ejiek** [comment]
Going to update drawable and get rid of icon this evening.
Aaaaaaand reopen this PR.

**Comment by dkanada** [comment]
I must have been wrong, thanks for catching the issue.

**Comment by ejiek** [comment]
It was not obvious at all.
You did a good job, thanks!

**Pull request merged**
