### PR TITLE
19 new icons

### PR DESCRIPTION
**Pull request by Donnnno**
I've created some new icons for: #388 #390 #394 #395

### CODE REVIEW

**Comment by Donnnno** [comment]
Oh, and also created an icon for my icon pack that should be on F-Droid soon™

**Comment by dkanada** [comment]
We should add links to each other's icon packs :) I can add a section sometime. I've wanted to remove the wallpapers for ages anyways, they aren't very useful and inflate the APK size by like 800% or something.

**Comment by Donnnno** [comment]
Yeah, Good idea! I already managed to change some things in the app (like removing wallpapers and changing colors). Btw the app code was pretty easy to understand for me (I'm not really a coder), so compliments to you for that :) 

The app was merged yesterday into the F-Droid data repo, so I hope it should be in the store quickly after that. (already waited like 2 months :s)

**Comment by dkanada** [comment]
I'm also hoping to eventually migrate a basic reimplementation of Turtl into this codebase so we can avoid a separate app for any icon requests. Although considering that's been on my list for several years at this point, I'm not sure I'll ever actually find the time to implement it haha.

**Comment by Donnnno** [comment]
Something like that would make a great addition to the app. But if it is too much work I can understand why it's still on a to-do list :)

**Pull request merged**
